name: Release Package

on:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: false

      # - run: sudo apt-get update && sudo apt-get install libboost-test-dev -y
      - name: Check signature
        run: |
          echo "${{ secrets.GPG_PUB_KEY }}" | gpg --import
          # gpg --list-keys
          KEY_FPR=$(gpg --list-keys --with-colons | grep '^fpr' | head -1 | cut -d: -f10)
          # echo "KEY_FPR: $KEY_FPR"
          echo "$KEY_FPR:6:" | gpg --import-ownertrust
          git verify-commit HEAD && echo "✅ Signature verified" || { echo "❌ Signature error" ; exit 1; }

      - run: cmake .
      - run: cmake --build .
      - run: cmake --build . --target test
      - run: cmake --build . --target package
      - name: Show deb packages
        run: |
          find . -maxdepth 1 -name "*.deb" -exec sh -c '
          echo "===== {} ====="
          dpkg-deb -I {}
          dpkg-deb -c {}
          ' \;

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          body:
          files: ./*.deb
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}


