name: Release Package

on:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      # - run: sudo apt-get update && sudo apt-get install libboost-test-dev -y

      - run: cmake .
      - run: cmake --build .
      - run: cmake --build . --target test
      - run: cmake --build . --target package
      - name: Show deb packages
        run: |
          find . -maxdepth 1 -name "*.deb" -exec sh -c '
          echo "===== {} ====="
          dpkg-deb -I {}
          dpkg-deb -c {}
          ' \;

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          body:
          files: ./*.deb
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}


